### ISSUE TITLE
Develop doesn't compile on Quartz with GCC 8.1.0

### ISSUE THREAD

**Issue by corbett5** [GEOSX/GEOSX#1550]
```
/usr/WS2/corbett5/geosx/GEOSX2/src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.cpp:567:12: error: ISO C++ forbids variable length array [-Wvla]
     real64 transmissibility[MAX_NUM_OF_CONNECTIONS][2], dTrans_dPres[MAX_NUM_OF_CONNECTIONS][2];
```

**Comment by klevzoff** [comment]
Seems to be a compiler bug fixed in gcc 8.4: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86429
We can probably work around by moving `constexpr` variable declarations inside the RAJA kernel here:
https://github.com/GEOSX/GEOSX/blob/a23824a6fc366c035a7a74f2adcd903882b8f12f/src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.cpp#L550-L552
