### ISSUE TITLE
debug build on quartz with gcc

### ISSUE THREAD

**Issue by andrembcosta** [GEOSX/GEOSX#2258]
Apparently, the most recent version of develop doesn't compile in debug mode with gcc 8.1 on quartz. 

`[ 40%] Building CXX object coreComponents/linearAlgebra/CMakeFiles/linearAlgebra.dir/interfaces/hypre/HyprePreconditioner.cpp.o
[ 40%] Building CXX object coreComponents/linearAlgebra/CMakeFiles/linearAlgebra.dir/interfaces/hypre/HypreSolver.cpp.o
In file included from /usr/workspace/macieira/new_geosx_folder/GEOSX/src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.hpp:22,
                 from /usr/workspace/macieira/new_geosx_folder/GEOSX/src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.cpp:19:
/usr/workspace/macieira/new_geosx_folder/GEOSX/src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirFVM.hpp: In member function 'void geosx::hypre::mgr::CompositionalMultiphaseReservoirFVM::setup(const geosx::LinearSolverParameters::MGR&, geosx::HyprePrecWrapper&, geosx::HypreMGRData&)':
/usr/workspace/macieira/new_geosx_folder/GEOSX/src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirFVM.hpp:133:28: error: 'HYPRE_MGRSetLevelFRelaxType' was not declared in this scope
     GEOSX_LAI_CHECK_ERROR( HYPRE_MGRSetLevelFRelaxType( precond.ptr, toUnderlyingPtr( m_levelFRelaxType ) ));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/workspace/macieira/new_geosx_folder/GEOSX/src/coreComponents/linearAlgebra/common/common.hpp:119:23: note: in definition of macro 'GEOSX_LAI_CHECK_ERROR'
     auto const ierr = call; \
                       ^~~~
/usr/workspace/macieira/new_geosx_folder/GEOSX/src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirFVM.hpp:133:28: note: suggested alternative: 'HYPRE_MGRSetFLevelRelaxType'
     GEOSX_LAI_CHECK_ERROR( HYPRE_MGRSetLevelFRelaxType( precond.ptr, toUnderlyingPtr( m_levelFRelaxType ) ));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~`

Apparently, it has something to do with the mgrStrategies and hypre.
